-- FROM절에 여러 테이블 사용하기
SELECT *
FROM EMP, DEPT
ORDER BY EMPNO;

SELECT * 
FROM EMP E ,DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

-- EMP테이블과 DEPT테이블을 JOIN, DEPTNO는 두 테이블에 모두 있으니깐 DEPTNO를 기준으로, SAL이 3000이상인 사원만 출력
SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND SAL >= 3000;

-- EMP, DEPT 급여가 2500 이하이고, 사원번호가 9999이하인 사원 출력
SELECT E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL < 2500
AND E.EMPNO <= 9999;

-- 비등가 조인
SELECT *
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- 사원 정보와 해당 사원의 직속상관의 사원번호를 나란히 출력
SElECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS "MGR_EMPNO", -- 매니저 사원번호
       E2.ENAME AS "MGR_ENAME" -- 매니저 이름 
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO; --E1의 MGR은 7566, 7698 ... 같은 사원 번호이고 ,E2의 EMPNO는 매니저 역할을 하는 테이블의 사원번호이다
-- 둘 다 동일한 테이블에 있는 정보이지만 다른 테이블인것 처럼 별칭을 다르게 설정 (E1 : 사원 역할, E2 : 매니저 역할)
-- E1의 MGR : 해당 사원의 매니저 사원 번호
-- E2의 EMPNO : 매니저의 사원 번호
-- 동일한 정보를 담고 있는 내용에 다른 별칭을 사용하여 하나의 테이블에서 조인하는 것

-- NATURAL JOIN
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
       DEPTNO, D.DNAME, D.LOC
FROM EMP E NATURAL JOIN DEPT D
ORDER BY DEPTNO, E.EMPNO;
-- 두 테이블 모두 DEPTNO가 있기 때문에 자동으로 DEPTNO를 조인 함

-- JOIN ~ USING
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
       DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D USING (DEPTNO)
WHERE SAL >= 3000
ORDER BY DEPTNO, E.EMPNO;
-- 두 테이블을 DEPTNO로 JOIN하고, 급여가 3000이상인 사원을 부서번호, 사원번호 순으로 출력 

-- JOIN ~ ON
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
       E.DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE SAL <= 3000
ORDER BY DEPTNO, E.EMPNO;

-- LEFT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.MGR,
       E2.EMPNO AS "MGR_EMPNO",
       E2.ENAME AS "MRG_ENAME"
FROM EMP E1 LEFT JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

-- RIGHT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.MGR,
       E2.EMPNO AS "MGR_EMPNO",
       E2.ENAME AS "MRG_ENAME"
FROM EMP E1 RIGHT JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

-- FULL OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.MGR,
       E2.EMPNO AS "MGR_EMPNO",
       E2.ENAME AS "MRG_ENAME"
FROM EMP E1 FULL JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

-- DEPTNO가 같을 때, 3000이상이며 직속상관이 있어야함
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
       DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D USING (DEPTNO)
WHERE E.SAL >= 3000
AND E.MGR IS NOT NULL
ORDER BY DEPTNO, ENAME;

-- 급여가 2000 초과인 사원들의 부서 정보, 사원 정보를 DEPTNO, DNAME, EMPNO, ENAME, SAL 부서번호 오름차순으로 출력
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM DEPT D JOIN EMP E 
ON D.DEPTNO = E.DEPTNO
WHERE SAL > 2000
ORDER BY D.DEPTNO ASC;

-- 각 부서별 평균 급여, 최대 급여, 최소 급여, 사원수를 출력
SELECT E.DEPTNO, D.DNAME, AVG(SAL) AS "AVG_SAL",
       MAX(E.SAL) AS "MAX_SAL", MIN(E.SAL) AS "MIN_SAL", COUNT(E.ENAME) AS "CNT"
FROM EMP E JOIN DEPT D
ON (E.DEPTNO = D.DEPTNO)
GROUP BY E.DEPTNO, D.DNAME
ORDER BY DEPTNO ASC;
-- GROUP BY를 사용할 때, SELECT절에 있는 컬럼 중 그룹 함수가 적용되지 않은 컬럼은 GROUP BY에 포함해야 한다.

-- DEPTNO, DNAME, EMPNO, ENAME, JOB, SAL을 다른 정보가 없어도 되도록 출력(OUTER JOIN)
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E RIGHT JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
ORDER BY D.DEPTNO, E.ENAME;

-- 부서 정보, 사원 정보, 급여 등급, 각 사원의 직속상관의 정보를 부서번호, 사원번호순으로 정렬
-- 테이블 세개를 조인 EMP, DEPT, SALGRADE
-- EMP의 SAL과 SALGRADE를 비등가 조인
-- EMP, DEPT를 조인
-- EMP를 E1, E2로 나눠서 하나는 사원 역할, 하나는 매니저 역할을 하게 조인
-- LEFT JOIN을 써서 40번 부서번호도 나오게 출력