-- 메뉴 테이블 생성
CREATE TABLE MENU (
    MENU_ID     NUMBER PRIMARY KEY,
    MENU_NAME   VARCHAR2(50),
    PRICE       NUMBER
);
DESC MENU;

SELECT * FROM MENU;


-- 메뉴 테이블 추가
INSERT INTO MENU VALUES (001, 'Ice_Americano', 3000);
INSERT INTO MENU VALUES (002, 'Hot_Americano', 2500);
INSERT INTO MENU VALUES (003, 'Cafe Latte', 4000);
INSERT INTO MENU VALUES (004, 'Strawberry_Smoothie', 5000);
INSERT INTO MENU VALUES (005, 'Blueberry_Smoothie', 4500);
INSERT INTO MENU VALUES (006,'Mango_Smoothie', 5000);
INSERT INTO MENU VALUES (007, 'Ice_Tea', 3000);
INSERT INTO MENU VALUES (008, 'Ice_Earl_Grey', 4000);
INSERT INTO MENU VALUES (009, 'Hot_Earl_Grey', 3500);
INSERT INTO MENU VALUES (010, 'Ice_Green_Tea', 3500);
INSERT INTO MENU VALUES (011, 'HOT_Green_Tea', 3200);
INSERT INTO MENU VALUES (012, 'Ice_Chamomile', 3200);
INSERT INTO MENU VALUES (013, 'Hot_Chamomile', 3500);
INSERT INTO MENU VALUES (014, 'Lemonade', 4000);
INSERT INTO MENU VALUES (015, 'Grapefruit_Ade', 5500);

-- 회원 테이블 : FastApi를 공부한 후 회원가입을 하면 자동으로 들어가는 구조
CREATE TABLE MEMBER (
    MEMBER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- GENERATED ALWAYS AS IDENTITY : 오라클이 자동으로 값을 만들어줌
    -- IDENTITY : 자동 번호 발급 기능
    MEM_NAME  VARCHAR2(10),
    TEL       VARCHAR2(20)
);
DESC MEMBER;

-- 주문 테이블
CREATE TABLE ORDERS (
    ORDER_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEMBER_ID   NUMBER,
    ORDER_DATE  DATE,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
    -- ORDERS.MEMBER_ID는 MEMBER.MEMBER_ID를 참조하는 외래키(FK)다.
);
DESC ORDERS;

-- 주문 상세 테이블
CREATE TABLE ORDERS_DETAIL (
    DETAIL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,    
    ORDER_ID  NUMBER,
    MENU_ID   NUMBER,
    PRICE     NUMBER,
    AMOUNT    NUMBER,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID)
);
DESC ORDERS_DETAIL;