-- DEPT 테이블을 복사한 DEPT_TEMP 테이블
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;
-- 확인
SELECT *
FROM DEPT_TEMP;

-- DEPT_TEMP에 부서번호 50, 부서명 DATABASE, 지역 SEOUL로 추가
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (50, 'DATABASE', 'SEOUL');
-- 확인 
SELECT * FROM DEPT_TEMP;

-- 열 지정 없이 60번 부서, NETWORK 부서명, BUSAN 지역 추가
INSERT INTO DEPT_TEMP
VALUES (60, 'NETWORK', 'BUSAN');
-- 확인
SELECT * FROM DEPT_TEMP;

-- NULL명시적 70, WEB, NULL
INSERT INTO DEPT_TEMP
VALUES (70, 'WEB', NULL);
-- NULL암시적 80, MOBILE, ''
INSERT INTO DEPT_TEMP
VALUES (80, 'MOBILE', '');
-- 확인
SELECT * FROM DEPT_TEMP;

-- 날짜 데이터 입력을 위해 EMP_TEMP테이블 생성
CREATE TABLE EMP_TEMP
AS SELECT * 
   FROM EMP
   WHERE 1 <> 1; -- 테이블의 구조는 똑같지만 데이터는 복사하고 싶지 않을 때 사용 1은 1과 같지 않다 : False로 결과적으로 행은 만들어지지 않음
-- 확인
SELECT * FROM EMP_TEMP;

-- 날짜 데이터 입력
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001/01/01', 5000, 1000, 10);
-- 확인
SELECT * FROM EMP_TEMP;
-- 추가
INSERT INTO EMP_TEMP
VALUES (1111, '성춘향', 'MANAGER', 9999, '2001-01-05', 4000, NULL, 20);
-- TO_DATE 활용
INSERT INTO EMP_TEMP
VALUES (2111, '이순신', 'MANAGER', 9999, TO_DATE('07/01/2001', 'DD/MM/YYYY'), 4000, NULL, 20);
-- SYSDATE 활용
INSERT INTO EMP_TEMP
VALUES (3111, '심청이', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);

-- S.GRADE = 1인 사원을 EMP_TEMP테이블에 추가해라
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND S.GRADE = 1;
SELECT * FROM EMP_TEMP;

-- 데이터 수정을 위한 테이블 복사
CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT;
-- 확인
SELECT * FROM DEPT_TEMP2;

-- 데이터 수정
-- 1) 데이터 전체 수정하기
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';
-- 확인 
SELECT * FROM DEPT_TEMP2;
-- 수정한 내용을 되돌리고 싶을 떄
ROLLBACK;

-- 2) 일부분 수정 : WHERE절 활용
UPDATE DEPT_TEMP2
SET DNAME = 'DATEBASE',
    LOC   = 'SEOUL'
WHERE DEPTNO = 40;

-- EMP_TEMP테이블의 사원들중에서 급여거 2500원 이하인 사원만 추가 수당을 50으로 수정하는 코드 작성
UPDATE EMP_TEMP
SET COMM = 50
WHERE SAL <= 2500;
SELECT * FROM EMP_TEMP;

-- 서브쿼리를 사용하여 데이터 수정하기 : DEPT테이블 40번 부서의 DNAME, LOC를 가져오는 서브쿼리
UPDATE DEPT_TEMP
SET (DNAME, LOC) = (SELECT DNAME, LOC  
                    FROM DEPT
                    WHERE DEPTNO = 40)
WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;

-- WHERE절에 서브쿼리 : DEPT_TEMP2 테이블의 부서 이름이 'OPERATIONS'인 지역이름을 'SEOUL'로 변경
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT_TEMP2
                WHERE DNAME = 'OPERATIONS');
SELECT * FROM DEPT_TEMP2;

-- 데이터 삭제를 위한 EMP_TEMP2 테이블 생성
CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP;
-- 확인
SELECT * FROM EMP_TEMP2;

-- 데이터 일부분만 삭제하기
DELETE EMP_TEMP2
WHERE JOB = 'MANAGER';
SELECT * FROM EMP_TEMP2;

-- 서브쿼리를 사용하여 데이터 삭제하기
-- 급여등급이 3등급인 30번 부서 사원 삭제하기
DELETE EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO
                FROM EMP_TEMP2 E, SALGRADE S
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                AND S.GRADE = 3
                AND E.DEPTNO = 30);
SELECT * FROM EMP_TEMP2;

-- 급여가 3000이상인 사원을 삭제하는 코드
DELETE EMP_TEMP2
WHERE SAL >= 3000;

-- 데이터 전체 삭제하기  : WHERE절에 아무것도 안적었을 때
DELETE EMP_TEMP2;
SELECT * FROM EMP_TEMP2;