CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

-- 1) CHAP10HW_DEPT테이블에 50, 60, 70, 80번 부서를 등록하는 코드 작성
SELECT * FROM CHAP10HW_DEPT;
-- INSERT INTO 50 ORACLE BUSAN / 60 SQL ILSAN / 70 SELECT INCHEON / 80 DML BUNDANG
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
VALUES (50, 'ORACLE', 'BUSAN');

INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
VALUES (60, 'SQL', 'ILSAN');

INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
VALUES (70, 'SELECT', 'INCHEON');

INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC)
VALUES (80, 'DML', 'BUNDANG');

-- 2) CHAPO10HW_EMP테이블에 8명의 사원 정보를 등록하는 코드 작성
SELECT * FROM CHAP10HW_EMP;

INSERT INTO CHAP10HW_EMP 
VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('2016-01-02', 'YYYY-MM-DD'), 4500, NULL, 50);

INSERT INTO CHAP10HW_EMP 
VALUES (7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('2016-02-21', 'YYYY-MM-DD'), 1800, NULL, 50);

INSERT INTO CHAP10HW_EMP 
VALUES (7203, 'TEST_USER3', 'ANALYST', 7201, TO_DATE('2016-04-11', 'YYYY-MM-DD'), 3400, NULL, 60);

INSERT INTO CHAP10HW_EMP 
VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('2016-05-31', 'YYYY-MM-DD'), 2700, 300, 60);

INSERT INTO CHAP10HW_EMP 
VALUES (7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('2016-07-20', 'YYYY-MM-DD'), 2600, NULL, 70);

INSERT INTO CHAP10HW_EMP 
VALUES (7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('2016-09-08', 'YYYY-MM-DD'), 2600, NULL, 70);

INSERT INTO CHAP10HW_EMP 
VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('2016-10-28', 'YYYY-MM-DD'), 2300, NULL, 80);

INSERT INTO CHAP10HW_EMP 
VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('2018-03-09', 'YYYY-MM-DD'), 1200, NULL, 80);

-- 3) CHAO10HW_EMP에 속한 사원중 50번 부서에서 근무하는 사원들의 평균 급여보다 많은 급여를 받는 사원들을 70번 부서로
-- 데이터 변경 : UPDATE, 서브쿼리
-- 50번 부서의 평균 급여 : 서브쿼리
SELECT AVG(SAL)
FROM CHAP10HW_EMP
WHERE DEPTNO = 50;

UPDATE CHAP10HW_EMP
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL)
             FROM CHAP10HW_EMP
             WHERE DEPTNO = 50);
SELECT * FROM CHAP10HW_EMP ORDER BY DEPTNO DESC;

-- 4) CHAP10HW_EMP에 속한 사원 중 60번 부서의 사원중에 입사일이 가장 빠른 사원보다 늦게 입사한 사원의 급여를 10%인상하고 80번 부서로 옮기는 코드
SELECT * FROM CHAP10HW_EMP;

SELECT MIN(HIREDATE) 
FROM CHAP10HW_EMP
WHERE DEPTNO = 60;

UPDATE CHAP10HW_EMP
SET DEPTNO = 80, SAL = SAL * 1.1
WHERE HIREDATE > (SELECT MIN(HIREDATE) 
                  FROM CHAP10HW_EMP
                  WHERE DEPTNO = 60);
SELECT * FROM CHAP10HW_EMP ORDER BY DEPTNO DESC;

-- CHAP10HW_EMP에 속한 사원 중 급여 등급이 5인 사원을 삭제하는 코드
-- 급여 등급을 구하는 서브쿼리
SELECT E.EMPNO
FROM SALGRADE S, CHAP10HW_EMP E
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE = 5;

DELETE CHAP10HW_EMP
WHERE EMPNO IN (SELECT E.EMPNO
          FROM SALGRADE S, CHAP10HW_EMP E
          WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
          AND S.GRADE = 5);
SELECT * FROM CHAP10HW_EMP;
-- 서브쿼리 부분에 E.EMPNO를 하는것이 좋다, S.GRADE가 아닌. EMPNO IN (~, ~, ~, ..., ~) 이런 형식이여서

-- 5) CHAP10HW_EMP에 속한 사원 중 60번 부서의 평균 급여보다 적게 받는 사원들의 급여를 20% 인상하시오.
-- 60번 부서의 평균 급여를 서브쿼리로 구할 것
-- 부서번호는 변경하지 않을 것

-- 60번 부서의 평균 급여
SELECT AVG(SAL)
FROM CHAP10HW_EMP
WHERE DEPTNO = 60;
-- 60번 부서보다 적게 받는 사원들의 급여 20% 인상
UPDATE CHAP10HW_EMP
SET SAL = SAL * 1.2
WHERE SAL < (SELECT AVG(SAL)
             FROM CHAP10HW_EMP
             WHERE DEPTNO = 60);

-- 6) 사원번호 7499인 사람을 70번 부서로 옮기고,
-- CHAP10HW_EMP에 속한 사원 중 70번 부서의 평균 급여보다 적게 받는 사원들을 삭제하시오.
-- 평균 급여는 서브쿼리로 구할 것
-- 70번 부서의 사원만 삭제하는 것이 아니라, 전체 사원 중 해당 평균보다 적게 받는 사원을 삭제할 것
UPDATE CHAP10HW_EMP
SET DEPTNO = 70
WHERE EMPNO = 7499;

-- 70번 부서의 평균 급여 구하기
SELECT AVG(SAL)
FROM CHAP10HW_EMP
WHERE DEPTNO = 70;

DELETE CHAP10HW_EMP
WHERE SAL < (SELECT AVG(SAL)
             FROM CHAP10HW_EMP
             WHERE DEPTNO = 70);
SELECT COUNT(*) FROM CHAP10HW_EMP;
-- 시작전 : 14, 한 후 : 7

-- 30번 부서에서 근무하는 사원 중, 해당 부서의 평균 급여보다 적게 받는 사원들의 급여를 10% 인상하시오.
-- 새로운 테이블 하나 만들기
CREATE TABLE NEW_EMP
AS SELECT * FROM EMP;
-- 30번 부서의 평균 급여 구하기
SELECT AVG(SAL)
FROM NEW_EMP
WHERE DEPTNO = 30;
-- 이 평균보다 작은 사원의 급여 10% 인상
UPDATE NEW_EMP
SET SAL = SAL * 1.1
WHERE SAL < (SELECT AVG(SAL)
             FROM NEW_EMP
             WHERE DEPTNO = 30)
AND DEPTNO = 30;
-- UPDATE에서 SET은 무엇을 변경할 것인가, WHERE은 누구를 변경할것인가 

-- 20번 부서에서 근무하는 사원 중, 20번 부서의 평균 급여보다 적게 받으면서 직책이 CLERK인 사원들의 급여를, 자기 부서(20번)의 평균 급여로 변경하시오.
-- 20번 부서의 평균 급여
SELECT AVG(SAL)
FROM NEW_EMP
WHERE DEPTNO = 20;

-- 평균보다 적은 사람 중 JOB = 'CLERK'인 사람의 급여를 평균 급여로 변경
UPDATE NEW_EMP
SET SAL = (SELECT AVG(SAL)
           FROM NEW_EMP
           WHERE DEPTNO = 20)
WHERE DEPTNO = 20
AND JOB = 'CLERK'
AND SAL < (SELECT AVG(SAL)
           FROM NEW_EMP
           WHERE DEPTNO = 20);