-- 중고 거래 총금액이 70만원 이상인 회원 id, 닉네임, 총거래금액 조회/총거래 기준 오름차순

-- 아이디별 거래 금액
-- SELECT WRITER_ID, SUM(PRICE)
-- FROM USED_GOODS_BOARD
-- WHERE STATUS = 'DONE'
-- GROUP BY WRITER_ID
-- HAVING SUM(PRICE) >= 700000;

-- 메인 
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS "TOTAL_SALES"
FROM USED_GOODS_USER U JOIN USED_GOODS_BOARD B
ON U.USER_ID = B.WRITER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY SUM(B.PRICE) ASC;
-- STATUS가 DONE인지 아닌지 확인