-- 2022년 1월 카테고리별 도서 판매량 합산하고 총 판매량 출력하는 SQL/카테고리 기준 오름차순

-- GROUP BY 카테고리 / JOIN / TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'/ SUM
SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;
-- TO_CHAR보다 날짜의 범위를 사용하는 편이 더 깔끔하다