-- 생산일자가 2022-05인 식품의 ID, 이름, 총매출을 조회하는 SQL
-- 총매출 기준으로 내림차순, 식품ID 오름차순
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, 
       SUM(O.AMOUNT * P.PRICE) AS "TOTAL_SALES"
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID ASC;
-- 총매출을 구하는것이여서 SUM을 사용해야함