-- 2022-01의 도서 판매데이터를 기준으로 저자별, 카테고리별 매출액을 구하여 
-- 저자ID, 저자명, 카테고리, 매출액 SQL/ 저자ID 오름차순, 카테고리 내림차순

-- AUTHOR/BOOK -> AUTHOR_ID
-- BOOK/BOOK_SALES -> BOOK_ID

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
       SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR A
ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;
-- 3개의 테이블을 JOIN하는 문제, 
-- TO_CHAR도 좋지만 밑의 방법도 좋음
-- WHERE S.SALES_DATE >= DATE '2022-01-01' 
-- AND S.SALES_DATE < DATE '2022-02-01'