-- 자동차의 종류가 '세단'인 자동차 중 10월에 대여 시작한 기록이 있는 차의 ID
-- 자동차 ID리스트는 중복 X, ID기준 내림차순으로

-- CAR_RENTAL_COMPANY_CAR 테이블에서 차종이 세단인 것 
-- SELECT CAR_ID
-- FROM CAR_RENTAL_COMPANY_CAR
-- WHERE CAR_TYPE = '세단'

-- CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블에 붙이고, 시작날짜 10월인것
SELECT DISTINCT(H.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단'
AND TO_CHAR(H.START_DATE, 'YYYY-MM') = '2022-10'
ORDER BY CAR_ID DESC;