-- 입양 간 동물중, 보호기간이 가장 길었던 동물 두마리의 아이디와 이름
-- 보호기간이 긴 순으로 조회

-- 서브쿼리
-- SELECT O.ANIMAL_ID
-- FROM ANIMAL_OUTS O JOIN ANIMAL_INS I
-- ON O.ANIMAL_ID = I.ANIMAL_ID
-- ORDER BY O.DATETIME - I.DATETIME DESC
-- FETCH FIRST 2 ROWS ONLY;

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IN (SELECT O.ANIMAL_ID
                      FROM ANIMAL_OUTS O JOIN ANIMAL_INS I
                      ON O.ANIMAL_ID = I.ANIMAL_ID
                      ORDER BY O.DATETIME - I.DATETIME DESC
                      FETCH FIRST 2 ROWS ONLY);