SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, 
       CAR_ID, 
       COUNT(*) AS RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                 WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08' 
                 AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10' 
                 GROUP BY CAR_ID HAVING COUNT(*) >= 5) 
GROUP BY MONTH, CAR_ID 
HAVING RECORDS <> 0 
ORDER BY MONTH ASC, CAR_ID DESC;

-- 안쪽 커리는 기간내 빌린 차의 ID를 잘 출력했지만, 바깥 커리에서는 그 자동차의 ID만 보고 빌린 횟수가 0이 아닌 차만 뽑아서 틀린 SQL문이다

-- 수정 
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH,
       CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
AND   CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08'
                  AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
                 GROUP BY CAR_ID
                 HAVING COUNT(*) >= 5)
GROUP BY MONTH, CAR_ID
HAVING RECORDS <> 0
ORDER BY MONTH ASC, CAR_ID DESC;
