-- 분기별 개체의 총 수를 구하는 문제

SELECT 
    -- 분기 구별
    CASE
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
        ELSE '4Q'
    END AS QUARTER,
    -- 카운트
    COUNT(CASE
            WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
            WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
            WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
            ELSE '4Q'
          END) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;

-- WITH절 사용으로 CASE문 한번만 사용 
WITH ECOLI_QUARTER AS (SELECT CASE
                               WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
                               WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
                               WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
                               ELSE '4Q'
                              END AS QUARTER
                       FROM ECOLI_DATA)
SELECT QUARTER, COUNT(*)
FROM ECOLI_QUARTER
GROUP BY QUARTER
ORDER BY QUARTER;