-- 각 년도별 최고길이를 먼저 구해야함 
-- SELECT EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY)
-- FROM ECOLI_DATA
-- GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)

-- 최고길이를 구한 SQL문을 WITH절로 이용하여 원래의 테이블과 JOIN
WITH MAX_LEN AS (SELECT EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR, 
                 MAX(SIZE_OF_COLONY) AS MAX_SIZE
                 FROM ECOLI_DATA
                 GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE))
SELECT M.YEAR, M.MAX_SIZE - D.SIZE_OF_COLONY AS YEAR_DEV, D.ID
FROM MAX_LEN M JOIN ECOLI_DATA D
ON M.YEAR = EXTRACT(YEAR FROM D.DIFFERENTIATION_DATE)
ORDER BY M.YEAR ASC, YEAR_DEV ASC;