-- 자신이 속한 부서의 평균 급여보다 높은 급여를 받는 사원을 조회하는 SQL문

-- 부서별 평균 급여를 구하는 SQL문
-- SELECT AVG(SAL), DEPT_CODE
-- FROM HR_EMPLOYEES
-- GROUP BY DEPT_CODE;

WITH AVG_SAL AS (SELECT AVG(SAL) AS BASIC, DEPT_CODE
                 FROM HR_EMPLOYEES
                 GROUP BY DEPT_CODE)
SELECT H.EMP_NO, H.EMP_NAME, A.DEPT_CODE, H.SAL
FROM HR_EMPLOYEES H JOIN AVG_SAL A
ON H.DEPT_CODE = A.DEPT_CODE
WHERE A.BASIC < H.SAL
ORDER BY H.SAL DESC, EMP_NO ASC;