-- 각 부서별로 급여가 가장 높은 사원을 조회

-- 부서별 가장 높은 급여 구하는 SQL
-- SELECT DEPT_CODE, MAX(SAL) AS MAX_SAL
-- FROM HR_EMPLOYEES
-- GROUP BY DEPT_CODE

WITH DEPT_SAL AS (SELECT DEPT_CODE, MAX(SAL) AS MAX_SAL
                  FROM HR_EMPLOYEES
                  GROUP BY DEPT_CODE)
SELECT H.EMP_NO, H.EMP_NAME, D.DEPT_CODE, H.SAL, H.HIRE_DATE
FROM HR_EMPLOYEES H JOIN DEPT_SAL D
ON D.DEPT_CODE = H.DEPT_CODE
WHERE H.SAL = D.MAX_SAL
ORDER BY D.DEPT_CODE ASC, H.EMP_NO DESC;