-- EMP 테이블을 복사하여 EMP_ALTER 테이블 생성하기
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

-- 테이블에 열을 추가하는 ADD : 테이블에 휴대폰 번호를 저장할 HP열
ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);
SELECT * FROM EMP_ALTER;

-- 열 이름을 변경하는 RENAME
ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;
SELECT * FROM EMP_ALTER;

-- 열의 자료형을 변경하는 MODIFY
ALTER TABLE EMP_ALTER
    MODIFY EMPNO NUMBER(5);
DESC EMP_ALTER;

-- 특정 열을 삭제하는 DROP
ALTER TABLE EMP_ALTER
    DROP COLUMN TEL;
SELECT * FROM EMP_ALTER;

-- 테이블 이름을 변경하는 RENAME
RENAME EMP_ALTER TO EMP_RENAME;

SELECT * FROM EMP_RENAME;

-- 테이블 데이터를 삭제하는 TRUNCATE
TRUNCATE TABLE EMP_RENAME;

-- 테이블을 삭제하는 DROP
DROP TABLE EMP_RENAME;
DESC EMP_RENAME;